name: Python CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'mod_net_client/**'
      - 'modules/test_module/**'
      - 'pyproject.toml'
      - 'requirements.txt'
      - '.github/workflows/python.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'mod_net_client/**'
      - 'modules/test_module/**'
      - 'pyproject.toml'
      - 'requirements.txt'
      - '.github/workflows/python.yml'

jobs:
  lint:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install UV
        run: pip install uv

      - name: Install dependencies
        run: uv sync --dev

      - name: Run Black
        run: uv run black mod_net_client modules/test_module --check

      - name: Run isort
        run: uv run isort mod_net_client modules/test_module --check-only --profile black

      - name: Run Ruff
        run: uv run ruff check mod_net_client modules/test_module tests

      - name: Run MyPy
        run: uv run mypy mod_net_client modules/test_module --ignore-missing-imports

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install UV
        run: pip install uv

      - name: Install dependencies
        run: uv sync --dev

      - name: Run tests
        run: |
          # Run tests with increased verbosity and coverage
          uv run python -m pytest tests/ -v --cov=mod_net_client --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: mod-net/module-pallet
