name: Python CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'mod_net_client/**'
      - 'modules/test_module/**'
      - 'pyproject.toml'
      - 'requirements.txt'
      - '.github/workflows/python.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'mod_net_client/**'
      - 'modules/test_module/**'
      - 'pyproject.toml'
      - 'requirements.txt'
      - '.github/workflows/python.yml'

jobs:
  lint:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Run Black + isort (fmt)
        run: nix run ./env-setup#fmt

      - name: Run Ruff (lint)
        run: nix run ./env-setup#lint

      - name: Run MyPy (typecheck)
        run: nix run ./env-setup#typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Run tests (pytest)
        run: nix run ./env-setup#test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: mod-net/module-pallet
