name: Rust CI (Nix)

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/rust.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/rust.yml'

jobs:
  nix-ci:
    name: Nix CI apps (fmt+lint+typecheck+test+docker-smoke)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
      - name: Run consolidated CI via Nix apps
        run: nix run ./env-setup#ci
